apiVersion: v1
kind: Service
metadata:
  name: well-healthy-backend-service
  namespace: well-health-care
spec:
  selector:
    app: well-health-backend
  ports:
    - protocol: TCP
      port: 8000 
      targetPort: 8000
  type: ClusterIP

