apiVersion: apps/v1
kind: Deployment
metadata:
  name: well-health-backend
  namespace: well-health-care
spec:
  replicas: 1
  selector:
    matchLabels:
      app: well-health-backend
  template:
    metadata:
      labels:
        app: well-health-backend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: backend
          image: well-health-backend:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
