apiVersion: v1
kind: Service
metadata:
  name: well-health-frontend-service
  namespace: well-health-care
spec:
  selector:
    app: well-health-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082
  type: NodePort